"""empty message

Revision ID: 564ae1728b51
Revises: 
Create Date: 2020-05-01 03:38:35.466053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '564ae1728b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_col', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('keys', sa.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('num_val', sa.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('cat_val', sa.ARRAY(sa.String(length=120)), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registries')
    # ### end Alembic commands ###
